version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/qiita-stocker-backend
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    mode: 777
    pattern: "**"
hooks:
  AfterInstall:
    - location: hooks/build.sh
      timeout: 1000
      runas: ec2-user
    - location: hooks/migration.sh
      timeout: 30
      runas: ec2-user
    - location: hooks/nginx-restart.sh
      timeout: 300
      runas: root
    - location: hooks/php-fpm-restart.sh
      timeout: 300
      runas: root
