version: '3.5'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    environment:
      PHP_HOST: php
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
